### ISSUE TITLE
Error to trying to run test

### ISSUE THREAD

**Issue by yhoseph** [bonitasoft/bonita-portal-js#132]
### **Error message**

---

```
'npm-run-all' is not recognized as an internal or external command,
operable program or batch file.
>> Tasks directory "tasks" not found.

```

**Comment by tsiakmaki** [comment]
I cannot deploy it either. 
http://127.0.0.1:9000/bonita/portaljs/ is a blank screen. 
I get errors like:
>> Tasks directory "tasks" not found.

Running "watch" task
Waiting...Fatal error: ENOENT: no such file or directory, open 'D:\git\bonita\bonita-portal-js-7.5.4\target\css\bonita-skin.css'

Could you please elaborate more on how to deploy the portal? 
Thank you.

**Comment by tsiakmaki** [comment]
Hi again. 
After various tests, I build the project (`yarn run build`)
and replaced the code at
`tomcat\server\webapps\bonita\portal.js`
with files exported at 
`bonita-portal-js-7.5.4\main` after build.

**Comment by tbouffard** [comment]
@tsiakmaki are you still facing an issue?
