### ISSUE TITLE
The main page is not displayed, it remains blank after loading

### ISSUE THREAD

**Issue by superrandres** [bonitasoft/bonita-portal-js#134]
Hello, I execute docker for bonita and bonita-portal-js, I to do this:
`docker run --name bonita --rm -d -p 8080:8080 bonita`
I can see http://localhost:8080/
On the other hand, I executed all the instructions for pretty-portal-js, obtaining as a result:
> Running "configureProxies:server" (configureProxies) task
Proxy created for: /bonita/apps to 172.17.0.4:8080
Proxy created for: /bonita/API to 172.17.0.4:8080
Proxy created for: /bonita/portal/ to 172.17.0.4:8080
Proxy created for: /bonita/services/ to 172.17.0.4:8080
Proxy created for: /bonita/theme/ to 172.17.0.4:8080
Running
"autoprefixer:dist" (autoprefixer) task
Prefixed file ".tmp/styles/bonita-theme.css" created.
Running "connect:livereload" (connect) task
Started connect web server on 0.0.0.0:9000.
Running "watch" task
Waiting...

But http://localhost:9000/bonita/portaljs/ finished on blank.

![captura de pantalla de 2018-06-11 10-36-46](https://user-images.githubusercontent.com/8306417/41241727-5bee717a-6d63-11e8-8d1c-1570bb0a7eae.png)

I need you help please!

**Comment by tbouffard** [comment]
@superrandres are you still facing this issue?
